server:
  port: 8888
security:
  basic:
    enabled: true
  user:
    name: pluralsight
    password: pluralsight
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: file://${user.home}/pluralsight-courses/springcloud-config-repo1
          #username: uname
          #password: pass
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - '*/perf'
              uri: file://${user.home}/pluralsight-courses/springcloud-config-repo2
              search-paths:
                - 'station*'
