debug: true
server:
  port: 8080
security:
  oauth2:
#    client:
#      client-id: pluralsight
#      client-secret: pluralsightsecret
#      access-token-uri: http://localhost:9001/services/oauth/token
#      user-authorization-uri: http://localhost:9001/services/oauth/authorize
#      client-authentication-scheme: form
#    resource:
#      user-info-uri: http://localhost:9001/services/user
#      prefer-token-info: false
  # well known credentials that will work with github, facebook and others. They ONLY work however,
  # when the client requesting the token is running on localhost port 8080...hence the server 
  # configuration in this file for server.port.
    client:
      clientId: bd1c0a783ccdd1c9b9e4
      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false